# Generated by Django 5.1 on 2024-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('date_reported', models.DateField()),
                ('date_of_occurrence', models.DateField()),
                ('time_of_occurrence', models.TimeField()),
                ('city', models.CharField(max_length=100)),
                ('crime_code', models.TextField()),
                ('crime_description', models.TextField()),
                ('victim_age', models.IntegerField()),
                ('victim_gender', models.CharField(max_length=10)),
                ('weapon_used', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_domain', models.CharField(max_length=100)),
                ('police_deployed', models.BooleanField(default=False)),
                ('case_closed', models.BooleanField(default=False)),
                ('date_case_closed', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
